# Generated by Django 2.1.1 on 2018-09-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180921_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mealpal_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mealpal_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
