# Generated by Django 2.1.1 on 2018-09-22 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mealrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
