# Generated by Django 2.1.1 on 2018-09-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mealrequest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealrequest',
            old_name='city_name',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='mealrequest',
            old_name='restaurant_name',
            new_name='meal_id',
        ),
        migrations.RenameField(
            model_name='mealrequest',
            old_name='timing',
            new_name='time',
        ),
        migrations.AddField(
            model_name='mealrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
