# Generated by Django 2.1.1 on 2018-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180925_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ENQUEUED', 'Enqueued'), ('NOT_ENQUEUED', 'Not Enqueued')], default='NOT_ENQUEUED', max_length=255),
        ),
    ]
